/*
 * Main.cpp - Expand_Shapes
 *
 * Description:
 *   This program generates expanded foreground and background pixel regions for each detected
 *   particle based on an input CSV of labeled pixel positions. These expanded regions can then
 *   be used to compute fluorescence traces for individual particles over time.
 *
 *
 * Input Arguments:
 *   argv[1]  - Path to CSV file with foreground pixel positions.
 *   argv[2]  - Path to CSV file with background pixel positions.
 *
 * Optional Flags:
 *   -BoundaryDist <float>         : Radius (pixels) for foreground inclusion zone (default: 4.1)
 *   -BackInnerRadius <float>      : Inner radius for background exclusion zone (default: BoundaryDist)
 *   -BackgroundDist <float>       : Radius (pixels) for background region (default: 20)
 *   -ExtraBackgroundFile <file>   : Optional CSV file specifying extra background pixels
 *   -Output <string>              : Output base name override
 *
 * Output Files:
 *   - Output files are generated by Expand_Shapes using the chosen output base.
 *
 * Dependencies:
 *   - BLCSVIO: Custom CSV parser for variable-width image region data.
 *   - BLTiffIO: Custom TIFF image I/O for saving masks.
 *   - BLFlagParser: Lightweight CLI flag parsing utility.
 *
 * Notes:
 *   - Pixel coordinates are stored in raster-order linear index format: `x + y * width`.
 *   - The first line in each output CSV contains image dimensions and pixel count.
 *   - Pixels are only assigned to foreground/background if they pass all distance and exclusion checks.
 *   - The geometric transformation supports rigid and affine alignment using 2D matrices and translations.
 *
 * @author James Walsh james.walsh@phys.unsw.edu.au
 * @date 2025-07-14
 */


#include <string>
#include <iostream>
#include <vector>
#include "BLFlagParser.h"


int Expand_Shapes( std::string foregroundposfile, std::string backgroundposfile, std::string extraBackgroundFileName, float boundaryDist, float backinnerradius, float backgroundDist, std::string output);

int main(int argc, char *argv[])
{

	float boundaryDist = 4.1f, backgroundDist = 20.0f, backinnerradius = 0.0f;

	std::string extraBackgroundFileName = "", outputfile = "";


	if (argc == 1 || (std::string(argv[1]).substr(0, 2) == "-h" || std::string(argv[1]).substr(0, 2) == "-H")) {
		std::cout << "Usage: Expand_Shapes <foreground_positions_csv> <background_positions_csv> [options]\n";
		std::cout << "Options:\n";
		std::cout << "-BoundaryDist f (Default f = 4.1) Foreground expansion radius.\n";
		std::cout << "-BackInnerRadius f (Default f = BoundaryDist) Background inner exclusion radius.\n";
		std::cout << "-BackgroundDist f (Default f = 20) Background expansion radius.\n";
		std::cout << "-ExtraBackgroundFile <file> Additional background positions CSV.\n";
		std::cout << "-Output <name> Override output base name.\n";
		return 0;
	}

	if (argc < 3) {
		std::cout << "Insufficient arguments.\n";
		std::cout << "Usage: Expand_Shapes <foreground_positions_csv> <background_positions_csv> [options]\n";
		return 1;
	}
	std::string foregroundposfile = argv[1];
	std::string backgroundposfile = argv[2];

	std::vector<std::pair<std::string, float*>> floatFlags = { {"BoundaryDist", &boundaryDist},{"BackInnerRadius", &backinnerradius},{"BackgroundDist", &backgroundDist} };
	std::vector<std::pair<std::string, std::string*>> stringFlags = { {"ExtraBackgroundFile", &extraBackgroundFileName},{"Output", &outputfile} };

	if (BLFlagParser::parseValues(floatFlags, argc, argv)) return 1;
	if (BLFlagParser::parseValues(stringFlags, argc, argv)) return 1;


	if (backinnerradius < boundaryDist)backinnerradius = boundaryDist;


	return Expand_Shapes( foregroundposfile, backgroundposfile, extraBackgroundFileName, boundaryDist, backinnerradius, backgroundDist, outputfile);

};
